---
#####################
## thesis metadata ##
#####################
title: Combining Extreme Value Theory and Statistical Learning
author: Matthew Pawley
date: Semester 2, 2020-21
supervisor: Dr Christian Rohrbeck
course: MA50215 Specialist Reading Course
department: Department of Mathematical Sciences
university: University of Bath
university-logo: templates/bath-logo.pdf

#####################
## FRONT MATTER ##
#####################
abstract: false
acknowledgements: false
dedication: false # if you want a dedication, write the words here
abbreviations: false #"front-and-back-matter/abbreviations" # path to .tex file with abbreviations

#######################
## bibliography path ##
#######################
bibliography: references.bib
bibliography-heading-in-pdf: Bibliography

########################
## PDF layout options ###
#########################

## correction highlighting ##
corrections: true

## binding / margins ##
# 'nobind' for equal margins (PDF output)
# 'twoside' for two-sided binding (mirror margins and blank pages)
# leave blank for one-sided binding (left margin > right margin)
page-layout: nobind

## position of page numbers ##
ordinary-page-number-foot-or-head: foot # 'foot' or 'head' 
ordinary-page-number-position: C  # C=centre, R=right, L=left. If page-layout='twoside', O=odd pages and E=even pages, e.g. RO,LE = right on odd and left on even
chapter-page-number-foot-or-head: foot # page number position on chapter pages
chapter-page-number-position: C

## position of running header ##
running-header: true # indicate current chapter/section in header?
running-header-foot-or-head: head
running-header-position-leftmark: LO # marks the chapter. If page-layout='nobind', only this is used.
running-header-position-rightmark: RE  # marks the section

draft-mark: true # add a draft mark? ("DRAFT + date")
draft-mark-foot-or-head: head # 'foot' or 'head' 
draft-mark-position: R

## section numbering ##
section-numbering-depth: 2 # depth of heading numbers

## tables of content ##
toc-depth: 2 # to which depth should headings be included in table of contents?
lof: false # include list of figures in front matter?
lot: false # include list of tables in front matter?
mini-toc: false  # include mini-table of contents at start of each chapter? (this just prepares it; need to also add \minitoc after each chapter title)
mini-lot: false  # include mini-list of tables by start of each chapter?
mini-lof: false  # include mini-list of figures by start of each chapter?

## bibliography style ##
bib-authoryear: true   # true to format references as author-year - false as numberic
doi-in-bibliography: true # true to show DOI's in the bibliography

## code block spacing ##
space-before-code-block: 10pt
space-after-code-block: 8pt

## linespacing ##
linespacing: 22pt plus2pt # 22pt is official for submission & library copies
frontmatter-linespacing: 17pt plus1pt minus1pt # spacing in roman-numbered pages (acknowledgments, table of contents, etc.)

### other stuff ###
abstractseparate: false  # creates an additional front cover with title and abstract (needed for some submissions)
hidelinks: false # hide the coloured links (e.g. citations, refs, urls)?

#####################
## output options  ##
#####################
output:
  bookdown::pdf_book:
    template: templates/template.tex
    keep_tex: true # keep the LaTeX file used to generate the PDF
    citation_package: biblatex  
    pandoc_args: "--lua-filter=scripts_and_filters/colour_and_highlight.lua"
  bookdown::bs4_book: 
    css: 
      - templates/bs4_style.css
      - templates/corrections.css # remove to stop highlighting corrections
    theme:
      primary: "#6D1919"
    repo: https://github.com/pawleymatthew/Combining-EVA-and-Statistical-Learning
    pandoc_args: "--lua-filter=scripts_and_filters/colour_and_highlight.lua"
  bookdown::gitbook:
    css: templates/style.css
    config:
      sharing:
        facebook: false
        twitter: no
        all: false
  bookdown::word_document2:
    toc: true   
link-citations: true
documentclass: book
always_allow_html: true # allows html stuff in word (.docx) output
knit: (function(input, ...) {bookdown::render_book(input, output_format = "bookdown::pdf_book")})
# you can clean up the files LaTeX generates by running file.remove(list.files(pattern = "*.(log|mtc|maf|aux|bbl|blg|xml)")) in the R console
#knit: (function(input, ...) {bookdown::render_book(input, output_format = "bookdown::bs4_book")})
#knit: (function(input, ...) {bookdown::render_book(input, output_format = "bookdown::gitbook")})
#knit: (function(input, ...) {bookdown::render_book(input, output_format = "bookdown::word_document2")})
---

```{r install_packages, include=FALSE}
source('scripts_and_filters/install_packages_if_missing.R')
```

```{r include=FALSE}
# GENERAL
library(knitr)
library(tidyverse)
library(RColorBrewer)
library(lattice)
library(plot3D)
library(UsingR)

# CLUSTERING
library(cluster)
library(maps)
library(mapdata)
library(geodist)

# PCA
library(Matrix)
```


<!--
This chunk refers to user-defined R files in /scripts_and_filters folder:
create_chunk_options : custom chunk options
wrap_lines : soft wrap lines in code
-->

```{r create_chunk_options, include=FALSE, eval=knitr::is_latex_output()}
source('scripts_and_filters/create_chunk_options.R')
source('scripts_and_filters/wrap_lines.R')
```

<!-- This chunk includes the front page content in HTML output -->

```{r ebook-welcome, child = 'front-and-back-matter/_welcome-ebook.Rmd', eval=knitr::is_html_output()}
```
